### ISSUE TITLE
Vytvořit distribuci a instalační profil

### ISSUE THREAD

**Issue by petrillek** [Drupalcz/csgov#1]
Jako vývojář chci snadno nainstalovat distribuci se základní konfigurací, volitelně pak extra moduly a výchozí obsah.

**Comment by jcerveny** [comment]
zkošel jsem instalaci "Use existing configuration" Install CS GOV using existing configuration.
Zkončil jsem chybou. viz. 
![csgov_instalace](https://user-images.githubusercontent.com/772501/58791628-de51e680-85f2-11e9-91aa-f291fda612e9.png)

**Comment by petrillek** [comment]
Na to už jsem taky narazil. Imho je tam nějaký problém v tom Password policy modulu. Pusť tu instalaci znovu a měla by doběhnout…

**Comment by petrillek** [comment]
Tady je k tomu issue: https://www.drupal.org/project/password_policy/issues/2771129

**Comment by jcerveny** [comment]
po aplikaci toho patche se mi to podařilo nainstalovat. Du se tím pořádně seznámit. díky

**Comment by miromichalicka** [comment]
@jcerveny ktory patch si pouzil? ja som skusil https://www.drupal.org/files/issues/2019-05-20/password_policy-config_import_field_error-2771129-81.patch a neodarilo sa ho aplikovat

**Comment by miromichalicka** [comment]
Na dev verziu to ide, @petrillek mame nejake policy ohladom dev verzii?

**Comment by miromichalicka** [comment]
Composer project - https://github.com/Drupalcz/csgov-project, treba zacat testovat. Na testovanie je potrebne si vyclonovat ten project a spustit `composer install` v ramci neho, kym @radimklaska nesprojazdni packagist.

**Comment by miromichalicka** [comment]
@petrillek spominal, ze chyba nejaky custom modul, treba ho pridat sem

**Comment by miromichalicka** [comment]
Modul je pridany, composer je vycisteny, packagist je funkcny. Zatvaram issue, ak su nejake problemy, tak ich budeme riesit v separatnych ticketoch.
