### ISSUE TITLE
Layout builder patch failed to apply

### ISSUE THREAD

**Issue by miromichalicka** [Drupalcz/csgov#12]
```
 Cannot apply patch Add suggestions for layout builder view modes. And apply the interdiff: https://www.drupal.org/files/issues/2019-04-17/interdiff.30013  
  13.17-21.patch (https://www.drupal.org/files/issues/2019-04-16/3001313-suggestions-19.patch)!
```

**Comment by miromichalicka** [comment]
> I'm of the opinion that this is not eligble for back-port to 8.7.x because it could have unintended consequences to templates/markup - see allowed changes - but its a grey area so I'll put it to a poll of other committers
https://www.drupal.org/project/drupal/issues/3001313#comment-13163451

**Comment by miromichalicka** [comment]
@petrillek co s tym? Dat novy patch? Aky je ucel toho patchu?

**Comment by petrillek** [comment]
Nový patch to řeší a funguje (mám vyzkoušené v praxi) https://www.drupal.org/files/issues/2019-06-17/3001313-41.patch. Takže ho klidně můžeme použít abychom se odblokli. A až vyjde 8.8, tak na ni přejít. Nevím jestli rovnou na Alpha nebo počkat apoň na betu.

**Comment by petrillek** [comment]
Jinak účelem toha patche je, aby renderoval obsah custom bloků se zvoleným view mode.
