### ISSUE TITLE
Installation process review

### ISSUE THREAD

**Issue by petrillek** [Drupalcz/csgov#13]
Potřebujeme aby instalační process byl:

* jednoduchý
* připravený pro CI
* dokumentovaný

**Comment by miromichalicka** [comment]
> připravený pro CI

ake CI chceme? Co tam ma vsetko bezat?

**Comment by petrillek** [comment]
> ake CI chceme? Co tam ma vsetko bezat?

To bylo spíš myšlené, abychom tam neměli něco co by případnému nasazení CI bránilo. Možná je to zbytečná poznámka.

**Comment by petrillek** [comment]
**Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2019-04-16/3001313-suggestions-19.patch**

– Tenhle patch byl commitnutý do 8.8.0.
– 8.8.0-alpha1 vyjde příští týden
– můžeme si v téhle fázi dovolit jít na 8.8. od aplha verze? RC vyjde cca za měsíc. Stable verze pak na začátku prosince.

Pokud ne tak musíme použít: https://www.drupal.org/files/issues/2019-06-17/3001313-41.patch

**Comment by petrillek** [comment]
Nový password policy patch – https://www.drupal.org/files/issues/2019-07-23/password_policy-n2771129-95.patch

**Comment by petrillek** [comment]
V config/install není core.extension.yml.

**Comment by miromichalicka** [comment]
pretoze moduly, ktore sa maju nainstalovat pre profil su v https://github.com/Drupalcz/csgov/blob/8.x-1.x/csgov.info.yml#L5, toto nie je projekt ale instalacny profil

**Comment by jcerveny** [comment]
Podařili se mi to v pohodě nainstalovat. Stáhl jsem platformu přes composer a pustil instalační profil CSgov.

**Comment by petrillek** [comment]
Instalace v současné podobě funguje dobře.
Uzavírám.
